services:
  - type: web
    name: presenton
    env: docker
    docker:
      image: ghcr.io/presenton/presenton:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: LLM
        value: google
      - key: GOOGLE_API_KEY
        sync: false   
      - key: GOOGLE_MODEL
        value: models/gemini-2.5-flash
      - key: IMAGE_PROVIDER
        value: gemini_flash
      - key: CAN_CHANGE_KEYS
        value: "false"
    disk:
      name: presenton-data
      mountPath: /app_data
      sizeGB: 1
